# Generated by Django 5.2.6 on 2025-09-25 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('request_update', 'Request Status Update'), ('provider_accepted', 'Provider Accepted Job'), ('provider_assigned', 'Provider Assigned'), ('job_started', 'Job Started'), ('job_in_transit', 'Job In Transit'), ('job_completed', 'Job Completed'), ('job_cancelled', 'Job Cancelled'), ('account_verified', 'Account Verified'), ('provider_verified', 'Provider Account Verified'), ('account_suspended', 'Account Suspended'), ('account_reactivated', 'Account Reactivated'), ('payment_pending', 'Payment Pending'), ('payment_confirmed', 'Payment Confirmed'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('deposit_received', 'Deposit Received'), ('bid_received', 'New Bid Received'), ('bid_accepted', 'Bid Accepted'), ('bid_rejected', 'Bid Rejected'), ('bid_counter_offer', 'Counter Offer Made'), ('message_received', 'New Message'), ('support_ticket_created', 'Support Ticket Created'), ('support_ticket_updated', 'Support Ticket Updated'), ('review_received', 'New Review Received'), ('rating_reminder', 'Rating Reminder'), ('system_maintenance', 'System Maintenance'), ('policy_update', 'Policy Update'), ('feature_announcement', 'New Feature'), ('account_warning', 'Account Warning'), ('payment', 'Payment Notification'), ('bid', 'Bid Notification'), ('message', 'New Message'), ('system', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('delivery_channels', models.JSONField(default=list, help_text='List of channels to deliver notification')),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Schedule notification for later', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('action_url', models.URLField(blank=True, help_text='URL for notification action', null=True)),
                ('action_text', models.CharField(blank=True, help_text='Text for action button', max_length=100, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When notification expires', null=True)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
