# Generated by Django 5.1.7 on 2026-09-27 00:10

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("region", "Region"),
                            ("city", "City or town"),
                            ("zone", "Zone"),
                        ],
                        default="zone",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("no_service", "No service"),
                        ],
                        db_index=True,
                        default="inactive",
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "boundary",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
            options={
                "ordering": ["kind", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "name"), name="uniq_service_area_kind_name"
                    )
                ],
            },
        ),
    ]
