# Generated by Django 5.2.6 on 2025-09-25 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Job', '0002_initial'),
        ('Request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='Request.request'),
        ),
    ]
