# Generated by Django 5.2.5 on 2025-09-29 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonItems', '0002_initial'),
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commonitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commonitem',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Specific service this item is available for', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Services.services'),
        ),
        migrations.AlterUniqueTogether(
            name='commonitem',
            unique_together={('name', 'category', 'type', 'brand', 'model', 'service')},
        ),
    ]
