# Generated by Django 5.2.6 on 2025-09-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommonItems', '0003_add_service_foreign_key_to_common_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='dimensions',
            field=models.JSONField(blank=True, help_text='Dimensions as JSON object', null=True),
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=8, null=True),
        ),
    ]
