# Generated by Django 5.1.7 on 2026-09-26 22:00

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Errand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "errand_type",
                    models.CharField(
                        choices=[
                            ("pickup", "Pickup"),
                            ("delivery", "Delivery"),
                            ("shopping", "Shopping"),
                            ("custom", "Custom task"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pickup_address", models.CharField(blank=True, max_length=500)),
                (
                    "pickup_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "pickup_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("dropoff_address", models.CharField(blank=True, max_length=500)),
                (
                    "dropoff_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "dropoff_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("price_pesewas", models.BigIntegerField()),
                ("commission_bps", models.PositiveIntegerField()),
                ("commission_pesewas", models.BigIntegerField()),
                ("agent_payout_pesewas", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In progress"),
                            ("delivered", "Delivered"),
                            ("completed", "Completed"),
                            ("disputed", "Disputed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("client_request_id", models.UUIDField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.CharField(blank=True, max_length=500)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_errands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_errands",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "errands",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ErrandEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("note", models.CharField(blank=True, max_length=500)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "errand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="errand.errand",
                    ),
                ),
            ],
            options={
                "db_table": "errand_events",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EscrowHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_pesewas", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("held", "Held"),
                            ("released", "Released to agent"),
                            ("refunded", "Refunded to customer"),
                        ],
                        db_index=True,
                        default="held",
                        max_length=20,
                    ),
                ),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "errand",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escrow",
                        to="errand.errand",
                    ),
                ),
            ],
            options={
                "db_table": "escrow_holds",
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stars", models.PositiveSmallIntegerField()),
                ("comment", models.CharField(blank=True, max_length=1000)),
                (
                    "errand",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="errand.errand",
                    ),
                ),
                (
                    "ratee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ratings",
            },
        ),
        migrations.AddIndex(
            model_name="errand",
            index=models.Index(
                fields=["customer", "status"], name="errands_custome_bdfc6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="errand",
            index=models.Index(
                fields=["agent", "status"], name="errands_agent_i_a12d34_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="errand",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_pesewas__gt", 0)),
                name="errand_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="errand",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("commission_pesewas__gte", 0),
                    ("agent_payout_pesewas__gte", 0),
                    (
                        "price_pesewas",
                        django.db.models.expressions.CombinedExpression(
                            models.F("commission_pesewas"),
                            "+",
                            models.F("agent_payout_pesewas"),
                        ),
                    ),
                ),
                name="errand_split_sums_to_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="errand",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_request_id__isnull", False)),
                fields=("customer", "client_request_id"),
                name="errand_client_request_id_unique_per_customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="escrowhold",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_pesewas__gt", 0)),
                name="escrow_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.CheckConstraint(
                condition=models.Q(("stars__gte", 1), ("stars__lte", 5)),
                name="rating_stars_1_to_5",
            ),
        ),
    ]
