# Generated by Django 5.1.7 on 2026-09-27 08:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("errand", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrandStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("pickup", "Pickup"), ("dropoff", "Drop-off")],
                        max_length=10,
                    ),
                ),
                ("address", models.CharField(max_length=500)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "errand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="errand.errand",
                    ),
                ),
            ],
            options={
                "db_table": "errand_stops",
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("errand", "position"),
                        name="errand_stop_position_unique",
                    )
                ],
            },
        ),
    ]
