# Generated by Django 5.2.6 on 2025-10-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
