# Generated by Django 5.1.7 on 2026-09-26 22:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("errand", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("escrow", "Escrow (held for errands)"),
                            ("platform", "Platform commission"),
                            ("payout_clearing", "Withdrawals awaiting payout"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("balance_pesewas", models.BigIntegerField(default=0)),
                ("currency", models.CharField(default="GHS", max_length=3)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "wallets",
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transfer_id", models.UUIDField(db_index=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("escrow_hold", "Escrow hold"),
                            ("escrow_release", "Escrow release to agent"),
                            ("commission", "Platform commission"),
                            ("escrow_refund", "Escrow refund"),
                            ("withdrawal_hold", "Withdrawal requested"),
                            ("withdrawal_reversal", "Withdrawal rejected"),
                            ("payout", "Withdrawal paid out"),
                            ("adjustment", "Admin adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount_pesewas", models.BigIntegerField()),
                ("balance_after_pesewas", models.BigIntegerField()),
                ("memo", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "errand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="errand.errand",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_pesewas", models.BigIntegerField()),
                ("reference", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("authorization_url", models.URLField(blank=True, max_length=500)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposits",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "deposits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_pesewas", models.BigIntegerField()),
                (
                    "network",
                    models.CharField(
                        choices=[
                            ("mtn", "MTN MoMo"),
                            ("telecel", "Telecel Cash"),
                            ("airteltigo", "AirtelTigo Money"),
                        ],
                        max_length=20,
                    ),
                ),
                ("momo_number", models.CharField(max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payout_reference", models.CharField(blank=True, max_length=100)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawals",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "db_table": "withdrawals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance_pesewas__gte", 0)),
                name="wallet_balance_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "user"), _negated=True),
                fields=("kind",),
                name="one_wallet_per_system_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "user"), ("user__isnull", False)),
                    models.Q(
                        models.Q(("kind", "user"), _negated=True),
                        ("user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="user_wallets_have_owner_system_wallets_do_not",
            ),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["wallet", "-created_at"], name="ledger_entr_wallet__b56567_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgerentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_pesewas", 0), _negated=True),
                name="ledger_amount_non_zero",
            ),
        ),
        migrations.AddConstraint(
            model_name="deposit",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_pesewas__gt", 0)),
                name="deposit_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="withdrawal",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_pesewas__gt", 0)),
                name="withdrawal_amount_positive",
            ),
        ),
    ]
