# Generated by Django 5.2.5 on 2025-10-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='base_location_data',
            field=models.JSONField(blank=True, help_text='Base location address and coordinate data', null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_areas_data',
            field=models.JSONField(blank=True, help_text='Service areas with address and coordinate data', null=True),
        ),
    ]
