# Generated by Django 5.2.6 on 2025-10-05 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Provider', '0003_add_json_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='service_areas_data',
        ),
    ]
